apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mlflow-server
  labels:
    app: mlflow-server
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: {{ .Release.Name }}-mlflow-server
        image: {{ .Values.image }}
        imagePullPolicy: Always
{{- if .Values.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- end }}
{{- if .Values.env }}
        env:
{{ toYaml .Values.env | indent 8 }}
{{- end }}
{{- if .Values.command }}
        command: {{ .Values.command }}
{{- end }}
{{- if .Values.args }}
        args: {{ .Values.args }}
{{- end }}
        ports:
        - containerPort: {{ default 80 $.Values.containerPort }}
{{- if .Values.volumes }}
      volumes:
{{ toYaml .Values.volumes | indent 6 }}
{{- end }}
